### PR TITLE
Add support for skin tones

### PR DESCRIPTION
**Pull request by tankerkiller125**
This pull request adds skin toned emoji to the map

### CODE REVIEW

**Comment by dsevillamartin** [comment]
Hm, not sure if this is the best way to handle skin tones, to be honest, as the file size increases from 40KB to 100KB.
Perhaps we can have a different file that contains a list of the emojis that support skin tones?

We could still have a setting for adding each individual one to the main JSON file - but it'd be off by default.

**Comment by tankerkiller125** [comment]
I'd be happy with a separate file, this pull request is mostly to resolve the auto-complete on the Emoji extension for Flarum (which supports tones, but can't auto-complete with tones) so if we add via a separate file and then upgrade the Flarum extension to load that new file I'd be pretty happy with that result.

**Comment by dsevillamartin** [comment]
Yeah I think the separate file is better - a file that only has a list of the emojis that support it, so then when parsing it can be looped like in the code you added here.

Though actually, some emojis support more than just 5 tones (since v12 - https://milesj.gitbook.io/emojibase/spec#v-12-0) so... not sure how to handle that with just a simple list. Perhaps simply have an object with the list of possible tones? Something like this:
```json
{
  "<shortcode>": [1, [1,2], [1,3], ..., 2, ..., 5]
}
```

**Comment by tankerkiller125** [comment]
The extra skin tones are already in the short code, for example `holding_hands_people_tone1-4` is two gender neutral people holding hands, first person being tone1 and the second person being tone4

Edit: Nevermind I see what your trying to say now.

**Comment by dsevillamartin** [comment]
I just remembered this PR exists. Should be good for merging, right??

**Comment by tankerkiller125** [comment]
The tones are now in a separate file, they aren't exported though, not sure how you want to handle that. Further it's just a list of short-codes and the respective emoji.

**Comment by dsevillamartin** [comment]
Merged this, not sure if I'll release because I think having a relationship between shortcodes & skin tones would be useful too. And not just skin tones necessarily, perhaps variants too. Not a priority though.

**Comment by tankerkiller125** [comment]
The variants do exist here, things like families with multiple skin tones are supported by the PR. It's probably not the most efficient thing though.

**Pull request merged**
